name: Feature 🧩
description: Feature
title: "|"
type: "Feature 🧩"
projects: ["StaytunedLLP/43"]

body:
  - type: textarea
    attributes:
      label: Issue Description
      value: |
        # Feature

        <!-- A concise title for the feature (4-6 words) -->
       
        ## Feature Details

        ### Purpose and Value

        <!-- Describe what this feature does and why it matters:
        - What problem does it solve?
        - How does it benefit users or the business?
        - Who is the target audience? (specific user personas) -->

        ### Priority

        <!-- Define priority based on pareto principle:
        - P1: 20% effort / 80% impact (high value, relatively easy)
        - P2: 80% effort / 20% impact (high effort for modest gains)
        -->

        ### Implementation Details

        <!-- Provide comprehensive details about the feature:
        - Functionality and capabilities
        - User interaction flow
        - Key components/elements
        - Navigation/access points -->

        ### Dependencies

        <!-- List systems, services, or technical dependencies, external api dependencies, etc -->

        ### Experience Design

        <!-- Define the user journey steps, touchpoints, and expected emotional response. Attach any relevant design mockups or wireframes using [Example link] format. -->

        ### Assumptions & Risks

        <!-- Identify risks and mitigation strategies -->

        ### Notes

        <!-- Any additional information or future considerations -->

        ### Related Features

        <!-- Features: #789 -->

        ### Stories

        <!-- Stories: #123, #456 -->

        ## Acceptance Criteria

        <!-- List specific, testable criteria that must be met for the feature to be considered complete.
        Each criterion should be clear, concise, and verifiable.
        - All user stories associated with this feature must be completed and pass their acceptance criteria.
        - The feature must be tested across all supported browsers and devices.
        - Documentation must be updated to reflect the new feature. -->

  - type: markdown
    attributes:
      value: |
        :yellow_circle: **CAUTION**
        1. The future is AI. Embrace it, or be left behind. :robot:
        1. Search existing issues first to avoid duplicates. :dancing_women:

        :red_circle: **IMPORTANT**
        1. First flag it, then ship it with confidence! :white_flag:
        1. Your insights matter! Report issues to drive a change. :pushpin:

        Add [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) if needed.
