name: Bug 🐞
description: Bug
title: "|"
type: "Bug 🐞"
projects: ["StaytunedLLP/43"]

body:
  - type: textarea
    attributes:
      label: Issue Description
      value: |
        # Issue Title

        <!-- Select type: [Bug | Feature Request | Enhancement | Task] -->

        ## Issue Details

        ### Purpose and Value

        <!-- Describe what this feature/fix does and why it matters:
        - What problem does it solve?
        - How does it benefit users or the business?
        - Who is the target audience? -->

        ### Priority

        <!-- Define priority based on pareto principle:
        - P1: 20% effort / 80% impact (high value, relatively easy)
        - P2: 80% effort / 20% impact (high effort for modest gains)
        -->

        ### Association

        <!-- Link related items:
        - Parent Feature/Story: #issue_number
        - Related Issues: #issue_number
        - Dependencies: #issue_number -->

        ### Context

        <!-- Provide:
        - For bugs: Steps to reproduce, expected vs actual behavior
        - For features: User story, business context
        - For enhancements: Current limitation, proposed improvement -->

        ### Notes

        <!-- Any screenshots, mockups, or relevant links -->

        ## Proposed Solution

        <!-- Step by step process to solve the problem/issue -->

        ## Acceptance Criteria

        <!-- List specific, measurable outcomes:
        - [ ] Feature functionality matches requirements
        - [ ] All edge cases and error scenarios handled
        - [ ] Unit tests added/updated with >80% coverage
        - [ ] Integration tests added/updated
        - [ ] Documentation updated (README, API docs, etc.)
        - [ ] Code review completed
        - [ ] Performance impact assessed
        - [ ] Security implications reviewed
        - [ ] Backward compatibility maintained
        - [ ] Logging and monitoring in place -->

  - type: markdown
    attributes:
      value: |
        :yellow_circle: **CAUTION**
        1. The future is AI. Embrace it, or be left behind. :robot:
        1. Search existing issues first to avoid duplicates. :dancing_women:

        :red_circle: **IMPORTANT**
        1. First flag it, then ship it with confidence! :white_flag:
        1. Your insights matter! Report issues to drive a change. :pushpin:

        Add [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) if needed.
