name: 🏳️ Flag
description: Specific actions to be completed.
title: "|"
type: "Flag 🏳️"
projects: ["StaytunedLLP/43"]

body:
  - type: textarea
    attributes:
      label: Issue Description
      value: |
        ## Feature Flag Name/Identifier

        ## Purpose/Motivation

        ## Intended Behavior (When Enabled)

        ## Intended Behavior (When Disabled)

        ## Rollout Strategy/Phases

        ## Activation Criteria

        ## Deactivation Criteria

        ## Testing Considerations

        ## Monitoring/Metrics

        ## Dependencies/Related Issues

        ## Open Questions/Considerations

        ## Acceptance Criteria

        ## Alternatives Considered (Optional)

        ## Risks/Mitigations (Optional)

        ## Implementation Details (Optional)
        
  - type: markdown
    attributes:
      value: |
        :yellow_circle: **CAUTION**  
        1. The future is AI. Embrace it, or be left behind. :robot:   
        1. Search existing issues first to avoid duplicates. :dancing_women:  

        :red_circle: **IMPORTANT**  
        1. First flag it, then ship it with confidence! :white_flag:  
        1. Your insights matter! Report issues to drive a change. :pushpin:   

        Add [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) if needed.