name: 🧩 Feature
description: New functionalities to be developed
title: "|"
type: "Feature 🧩"
projects: ["StaytunedLLP/43"]

body:
  - type: textarea
    attributes:
      label: Issue Description
      value: |
        ## Feature Summary 
        
        1. 

        ## Problem Statement

        1.

        ## Proposed Solution

        

        ## Alternatives Considered

        1.

        ## Additional Context

        1.

        ## Acceptance Criteria

        1.

        ## Feature Folder Location

        Add link here
        
  - type: markdown
    attributes:
      value: |
        :yellow_circle: **CAUTION**  
        1. The future is AI. Embrace it, or be left behind. :robot:   
        1. Search existing issues first to avoid duplicates. :dancing_women:  

        :red_circle: **IMPORTANT**  
        1. First flag it, then ship it with confidence! :white_flag:  
        1. Your insights matter! Report issues to drive a change. :pushpin:   

        Add [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) if needed.