name: 📝 Proposal 
description: Request changes or introduce new concepts
title: "|"
type: "Proposal 📝"
projects: ["StaytunedLLP/43"]

body:
  - type: textarea
    attributes:
      label: Issue Description
      value: |
        ## Purpose
        
        1. 

        ## Objectives

        1.

        ## Problem Statement

        1. 

        ## Proposed Solution

        1. 

        ## Benefits

        1.

        ## Alternatives Considered
        
        1.
        
        ## Action Plan

        1. 
        
        ## Resources Required

        1.

        ## Potential Risks
        
        1.
        
        ## Dependencies

        1. 

        ## Additional Context

        1.
        
  - type: markdown
    attributes:
      value: |
        :yellow_circle: **CAUTION**  
        1. The future is AI. Embrace it, or be left behind. :robot:   
        1. Search existing issues first to avoid duplicates. :dancing_women:  

        :red_circle: **IMPORTANT**  
        1. First flag it, then ship it with confidence! :white_flag:  
        1. Your insights matter! Report issues to drive a change. :pushpin:   

        Add [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) if needed.