name: 01_Dagger / Node build | Dagger

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/01_dagger_node_build.yml
      - src/01_dagger_24Aug2024/1_building_nodejs/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call Local Dagger Module
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: src/01_dagger_24Aug2024/1_building_nodejs/nodebuild/
          args: run-pipeline --source="src/01_dagger_24Aug2024/1_building_nodejs/project"
