name: 02_dagger_08Nov2024/2.building-a-basic-pipeline

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/fmt.yml
      - src/02_dagger_08Nov2024/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call Local Dagger Module
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: src/02_dagger_08Nov2024/2.building-a-basic-pipeline
          args: format --source="src/02_dagger_08Nov2024"
